name: Build and publish Cocobot's docker image

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

      - name: Build docker image
        run: docker build ./ -t ${{ secrets.DOCKER_USERNAME }}/cocobot:app

      - name: Push docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cocobot:app
